import { card } from "./card";

export const Cards: card[] = [
    { suite: 'D', rank: 'K', color: 'R', face: false},
    { suite: 'D', rank: 'Q', color: 'R', face: false},
    { suite: 'D', rank: 'J', color: 'R', face: false},
    { suite: 'D', rank: '10', color: 'R', face: false},
    { suite: 'D', rank: '9', color: 'R', face: false},
    { suite: 'D', rank: '8', color: 'R', face: false},
    { suite: 'D', rank: '7', color: 'R', face: false},
    { suite: 'D', rank: '6', color: 'R', face: false},
    { suite: 'D', rank: '5', color: 'R', face: false},
    { suite: 'D', rank: '4', color: 'R', face: false},
    { suite: 'D', rank: '3', color: 'R', face: false},
    { suite: 'D', rank: '2', color: 'R', face: false},
    { suite: 'D', rank: '1', color: 'R', face: false},
    { suite: 'H', rank: 'K', color: 'R', face: false},
    { suite: 'H', rank: 'Q', color: 'R', face: false},
    { suite: 'H', rank: 'J', color: 'R', face: false},
    { suite: 'H', rank: '10', color: 'R', face: false},
    { suite: 'H', rank: '9', color: 'R', face: false},
    { suite: 'H', rank: '8', color: 'R', face: false},
    { suite: 'H', rank: '7', color: 'R', face: false},
    { suite: 'H', rank: '6', color: 'R', face: false},
    { suite: 'H', rank: '5', color: 'R', face: false},
    { suite: 'H', rank: '4', color: 'R', face: false},
    { suite: 'H', rank: '3', color: 'R', face: false},
    { suite: 'H', rank: '2', color: 'R', face: false},
    { suite: 'H', rank: '1', color: 'R', face: false},
    { suite: 'S', rank: 'K', color: 'B', face: false},
    { suite: 'S', rank: 'Q', color: 'B', face: false},
    { suite: 'S', rank: 'J', color: 'B', face: false},
    { suite: 'S', rank: '10', color: 'B', face: false},
    { suite: 'S', rank: '9', color: 'B', face: false},
    { suite: 'S', rank: '8', color: 'B', face: false},
    { suite: 'S', rank: '7', color: 'B', face: false},
    { suite: 'S', rank: '6', color: 'B', face: false},
    { suite: 'S', rank: '5', color: 'B', face: false},
    { suite: 'S', rank: '4', color: 'B', face: false},
    { suite: 'S', rank: '3', color: 'B', face: false},
    { suite: 'S', rank: '2', color: 'B', face: false},
    { suite: 'S', rank: '1', color: 'B', face: false},
    { suite: 'F', rank: 'K', color: 'B', face: false},
    { suite: 'F', rank: 'Q', color: 'B', face: false},
    { suite: 'F', rank: 'J', color: 'B', face: false},
    { suite: 'F', rank: '10', color: 'B', face: false},
    { suite: 'F', rank: '9', color: 'B', face: false},
    { suite: 'F', rank: '8', color: 'B', face: false},
    { suite: 'F', rank: '7', color: 'B', face: false},
    { suite: 'F', rank: '6', color: 'B', face: false},
    { suite: 'F', rank: '5', color: 'B', face: false},
    { suite: 'F', rank: '4', color: 'B', face: false},
    { suite: 'F', rank: '3', color: 'B', face: false},
    { suite: 'F', rank: '2', color: 'B', face: false},
    { suite: 'F', rank: '1', color: 'B', face: false}

  ]